# Generated by Django 3.1.2 on 2022-05-25 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0002_auto_20220522_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesadvertisement',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_adv', to='advertisements.advertisement'),
        ),
        migrations.AlterField(
            model_name='favoritesadvertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
